#pragma once

#define PLUGIN_BUILD 1
#define PLUGIN_DESC L"The library is skeleton"
#define PLUGIN_NAME L"Skeleton"
#define PLUGIN_FILENAME L"skeleton.dll"
#define PLUGIN_AUTHOR L"Alexander Nesterov"
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR, FARMANAGERVERSION_MINOR, FARMANAGERVERSION_REVISION, PLUGIN_BUILD, VS_RELEASE)
